on: [push]

name: test

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        test: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    steps:
    - run: hostname
    - run: printenv
    - run: echo ${{ matrix.test }}
    - uses: actions/upload-artifact@v2
      with:
        path: |
          **/*.txt
          **/plot_*.svg
