on: [push]

name: test

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {tag: "bionic"}
          - {tag: "focal"}
          - {tag: "groovy"}
          - {tag: "hirsute"}
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    env:
    steps:
    - run: hostname
    - run: printenv
    - run: df -h .
    - uses: actions/upload-artifact@v2
      with:
        path: |
          **/*.txt
          **/plot_*.svg
