on: [push]

name: test

jobs:
  ubuntu:
    strategy:
      fail-fast: false
    env:
      GHA_EXTERNAL_DISK: "perf-tool-ci"
      GHA_PREEMPTIBLE: "false"
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    steps:
    - run: hostname
    - run: printenv
    - run: df -h
    - run: mount
    - uses: actions/upload-artifact@v2
      with:
        path: |
          **/*.txt
          **/plot_*.svg
